apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api
- ui
- database
- ingress
secretGenerator:
- envs:
  - migrations.env
  name: migrations
  namespace: api
- envs:
  - api.env
  name: api
  namespace: api
- envs:
  - database.env
  name: database
  namespace: database
generatorOptions:
  disableNameSuffixHash: true
