apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
  namespace: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy: {}
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/node-microservices-demo/microservices-demo/ui
        name: ui
        resources:
          limits:
            cpu: 200m
            memory: 45Mi
          requests:
            cpu: 200m
            memory: 45Mi

status: {}
