apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-manifests.yaml
- istio-operator.yaml
- namespace.yaml
- gateway.yaml
- istio-operator-crds.yaml
- peerauthentication.yaml
- kiali.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.14/samples/addons/prometheus.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.14/samples/addons/jaeger.yaml
